---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuxt-mono-deployment
  labels:
    app: nuxt-mono
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nuxt-mono-app
  template:
    metadata:
      labels:
        app: nuxt-mono-app
    spec:
      containers:
      - name: nuxt-mono
        image: ghcr.io/funng-guys/nuxt-mono:main
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: nuxt-mono-service
spec:
  selector:
    app: nuxt-mono-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nuxt-mono-ingress
spec:
  defaultBackend:
    service:
      name: nuxt-mono
      port:
        number: 80